/* error codes */
module.exports = {
  ZWARN_INVALID_OPTION: 2,
  ZERROR_TOO_LONG: 5,
  ZERROR_INVALID_DATA: 6,
  ZERROR_INVALID_CHECK: 7,
  ZERROR_INVALID_OPTION: 8,
  ZERROR_ENCODING_PROBLEM: 9,
  ZERROR_FILE_ACCESS: 10,
  ZERROR_MEMORY: 11
};