module.exports = {
  BARCODE_NO_ASCII: 1,
  BARCODE_BIND: 2,
  BARCODE_BOX: 4,
  READER_INIT: 16,
  SMALL_TEXT: 32,
  BOLD_TEXT: 64,
  CMYK_COLOUR: 128,
  BARCODE_DOTTY_MODE: 256,
  GS1_GS_SEPARATOR: 512
};